export const types = {
    GET_ITEMS: 'ITEMS_GET',
    GET_ONE_ITEM: 'ONE_ITEM_GET',
    CART_ADD: 'CART_ADD',
    CART_DELETE: 'CART_DELETE',
    CART_BUY: "CART_BUY",
    SORT_BY: 'SORT_BY',
    FILTER_CATEGORY: 'FILTER_CATEGORY',
    FILTER_TYPE: 'FILTER_TYPE',
}