export const types = {
	SET_LOADED: 'SET_LOADED',
	GET_ITEMS: 'ITEMS_GET',
	GET_ONE_ITEM: 'ONE_ITEM_GET',
	BASKET_ADD: 'BASKET_ADD',
	BASKET_DELETE: 'BASKET_DELETE',
	BASKET_BUY: 'BASKET_BUY',
	BASKET_CLEAR: 'BASKET_CLEAR',
	FILTER: 'FILTER_BY',
	FILTER_CATEGORY: 'FILTER_CATEGORY',
	FILTER_TYPE: 'FILTER_TYPE',
	FILTER_BRAND: 'FILTER_BRAND',
}